// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgdi76tbg1ks-Il30GZlBzlwAK1yUvkOY',
    appId: '1:128548308672:web:407acc6720c7d48b99cf25',
    messagingSenderId: '128548308672',
    projectId: 'btack-ec70f',
    authDomain: 'btack-ec70f.firebaseapp.com',
    storageBucket: 'btack-ec70f.appspot.com',
    measurementId: 'G-611HDXNG9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN8KOCjk5kTUVEoyqyDKoQubNIHo_dlBg',
    appId: '1:128548308672:android:1f37f63e795ab83e99cf25',
    messagingSenderId: '128548308672',
    projectId: 'btack-ec70f',
    storageBucket: 'btack-ec70f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInOqPZvkgrRWXyGpsxkJ5JRvNlZJhE3E',
    appId: '1:128548308672:ios:64362e4ec2b67e5999cf25',
    messagingSenderId: '128548308672',
    projectId: 'btack-ec70f',
    storageBucket: 'btack-ec70f.appspot.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCInOqPZvkgrRWXyGpsxkJ5JRvNlZJhE3E',
    appId: '1:128548308672:ios:4f43a37261f3a15c99cf25',
    messagingSenderId: '128548308672',
    projectId: 'btack-ec70f',
    storageBucket: 'btack-ec70f.appspot.com',
    iosBundleId: 'com.example.financeApp.RunnerTests',
  );
}
